### ISSUE TITLE
Plugin breaks if a nickname with a dot symbol is added

### ISSUE THREAD

**Issue by xairaven** [NobelD/NobleWhitelist#1]
### Console Log:
[Pastebin of all the log](https://pastebin.com/NN6n88hG)

### Bug behaviour:
The server with the plugin is running. 
I add a nickname with a dot symbol, for example, “vi.hnu”: `/nwl add name vi.hnu`
After this whitelist.yml breaks: 
```yml
whitelist:
    xairaven: <some-uuid>
    vi:
        hnu: none
    example$ThisNameShouldNotBeAPlayerName$1234567: uuid-1234
```
The next time, when I start the server, I get an exception (visible in a log file).

### What im expected to happen
Whitelist.yml:
```yml
whitelist:
    xairaven: <some-uuid>
    vi.hnu: none
    example$ThisNameShouldNotBeAPlayerName$1234567: uuid-1234
```
Manual file editing fixes the problem

### Version
Plugin version: `1.0.2`
Minecraft version: `1.20.2`
Paper version: `1.20.2-246`
