### ISSUE TITLE
player uuid not being picked up 

### ISSUE THREAD

**Issue by Konoyon** [NobelD/NobleWhitelist#2]
When me and others do /whitelist add <name> the only i id it pulls is the discord id but no minecraft uuid.

**Comment by NobelD** [comment]
The command is `/nwl` or `/nwhitelist`, not `/whitelist`, that is the vanilla command.
If you are still having issues can you explain it better?

You can also send the literal command or a screenshot of the command for better support.

**Comment by Konoyon** [comment]
![image_2024-01-23_211448251](https://github.com/NobelD/NobleWhitelist/assets/74889458/6f8fc3a5-8ac9-4f41-82e9-8d446badb909)

/nwl and /nwhitelist works in minecraft and the console but with the discord addon do i need to addon  uuid

**Comment by Konoyon** [comment]
![image_2024-01-23_212319855](https://github.com/NobelD/NobleWhitelist/assets/74889458/afb512a0-754b-4ed9-a3ff-0a7e4d30e789)

**Comment by NobelD** [comment]
Oh, I was thinking you were talking about the base plugin not about the discord integration.

Well, the uuid is intended to not be inputed by the user, as most players don't even know their exact uuid.
When they join the server the uuid part is automatically filled.
(And the user id is to prevent players from adding too many accounts, a limit of accounts will be added later).

The player uuid is different between online and offline players so it can be difficult for users.

Also the uuid field for the command will be added later, I am working on other things so when I have time I will add it.

**Comment by Konoyon** [comment]
thats the part that im having trouble with is that when they join the server the uuid isn't filled automatically with the account.

**Comment by NobelD** [comment]
That's weird, i think you probably have the whitelist off.
Also can you share me your config.yml?

**Comment by Konoyon** [comment]
https://pastebin.com/U3RPdi0j

**Comment by Konoyon** [comment]
```yml
# All the config will dynamically be changed, is not necessary to reload the config.
# The whitelist config is read only, if you change data is necessary make a reload.
# Prefer to use the commands before editing the whitelist config.
whitelist: 
  # Alternate the whitelist will dynamically be changed.
   enabled: true
  # Will disable the name change in the whitelist config if the player joins with the same uuid but different name.
  # If you have a low-performance server this can help a little.
   skip-name-change: false
  # Posible values for checking:
  # DISABLED - will not be used when checking.
  # OPTIONAL - will be an option when checking.
  # REQUIRED - will be necessary for the player
  # if all disabled, then the whitelist will not block players even if its enabled.
  # The bypass permission is "noblewhitelist.bypass" or had op.
  # If name and uuid are required, then this will not allow adding players with the command if both the name and uuid are not specified.
   checking: 
      name: OPTIONAL
      uuid: OPTIONAL
      perm: DISABLED
  # If the player who is op is considered as a bypass player.
   count-op-as-bypass: true
  # If enabled and the whitelist is disabled, then will auto register the name and uuid of the player.
  # Useful if you want to enable the whitelist time later and keep the players who joined in the whitelist.
   auto-register: false
  # This will block if a player joins with the same name as another registered player but with a different uuid.
  # If you have a server with online and offline uuid players at the same time, ensure that the online player is well registered.
   enforce-uuid-if-different-name: true
storage: 
  # The storage type to be used, migration of data is made manually.
  # It's necessary to restart the server to apply changes.
  # mysql - Remote storage that can be used in multiple server.
  # sqlite - Faster storage for easy management when expecting a lot of players.
  # yaml - Simple editable storage and easy to use.
  # json - Faster storage than yaml, a little confusing to read.
   storage-type: json
  # It's not necessary to fill unless using remote databases.
   host: ""
   port: 3306
   database: ""
   user: ""
   password: ""
  # The server will be closed if the plugin cannot load the database, for security reasons.
   close-if-failed: false
messages: 
   prefix: <bold><#17B90C>N<#7FD024>Whitelist</bold> <grey>>
   use-prefix: true
  # Placeholders:
  # <player> = Player name
  # <prefix> = Message prefix (if disabled will not be showed)
   not-whitelisted: <blue>You are not whitelisted on this server.
  # This message will be sent to the console when a player joins with the same uuid but different name.
   name-change-console: <prefix><yellow><name> has joined with another name (probably a premium player)
   name-change-player: <green>Successfully validated uuid, welcome back <name>!
version: 
  # Notify when there is a new update.
   notify-update: true
   version: 2
```
