### ISSUE TITLE
[Feature Request] Plugin localization and replace minecraft:whitelist command

### ISSUE THREAD

**Issue by marat2509** [NobelD/NobleWhitelist#7]
Hello.

Thank you for this plugin ❤️

I request you to add the following functionality to your plugin:

1. localization (at least command messages)

I would like to be able to receive commands messages in native language (which will be added by community members). I for example am ready to add Russian language if you will implement this functionality

2. Possibility to replace the standard /whitelist command (and possibly disable Minecraft's built-in whitelist mechanism).
It is expected to be possible to include in config.yaml to replace the standard /whitelist command with the functionality of the /nwl command.
Better yet, implement it in the alias column for the noblewhitelist command.

Example of new settings in config.yml:

```yaml

command:
  aliases:
    - "wl"         # /wl -> /noblewhitelist.
    - "whitelist"  # /wl -> /noblewhitelist

  disable-minecraft-whitelist: true
  # disables /minecraft:whitelist commands and default minecraft whitelist functional
```

Thank you for your contribution to the open source community ❤️
